### ISSUE TITLE
Pip install failing - unable to find build_tools

### ISSUE THREAD

**Issue by richard-moss** [pydicom/pylibjpeg-openjpeg#45]
***Background***

I'm using a M1 mac mini dev machine, and have previously been using Anaconda based conda for managing environments.  This only presently supports using mac x86 versions of everything, which while they work, use mac's rosetta to run the x86 code non-natively.

So I'm cleaning all that cruft out, and using native miniconda mac-arm versions of everything.

Everything has worked fine with installing native python and all the modules I use, right up until pylibjpeg.  (Including pydicom, which uses `noarch` version and runs perfectly it seems so far).

***Problem***

Using pip (specifically miniconda's pip) to install pylibjpeg fails when trying to install pylibjpeg-openjpeg:

The problem is pip is pullling down `pylibjpeg-openjpeg-1.1.1.tar.gz`, and then `setup.py` is failing as its unable to find CMakeLists.txt.

A quick check by manually downloading `pylibjpeg-openjpeg-1.1.1.tar.gz` shows that the entire `build_tools` directory is missing:

```
(aqs-tests-2)  pylibjpeg-openjpeg-1.1.1 >> ls
MANIFEST.in                 README.md                   pylibjpeg_openjpeg.egg-info setup.py
PKG-INFO                    openjpeg                    setup.cfg
(aqs-tests-2)  pylibjpeg-openjpeg-1.1.1 >> find . -name build_tools
(aqs-tests-2)  pylibjpeg-openjpeg-1.1.1 >> ls openjpeg/
__init__.py   _openjpeg.pyx _version.py   src           tests         utils.py
```

**Question**
Should I be using a specific (different) tarball instead of what pip's defaulting to (`pylibjpeg-openjpeg-1.1.1.tar.gz`)?

***Pip Install output:***

```
Conda-arm-install-stuff >> pip download pylibjpeg
Collecting pylibjpeg
  Downloading pylibjpeg-1.3.0-py3-none-any.whl (28 kB)
Collecting pylibjpeg-openjpeg
  Downloading pylibjpeg-openjpeg-1.1.1.tar.gz (2.3 MB)
     |████████████████████████████████| 2.3 MB 2.1 MB/s 
    ERROR: Command errored out with exit status 1:
     command: /Users/rjm/miniforge3/envs/aqs-tests-2/bin/python3.8 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/t3/6rfnr3rd6jl7_jg08ppg5h3c0000gq/T/pip-download-3opfmxjo/pylibjpeg-openjpeg_93f9a1031bbc467692cd36833771bcd2/setup.py'"'"'; __file__='"'"'/private/var/folders/t3/6rfnr3rd6jl7_jg08ppg5h3c0000gq/T/pip-download-3opfmxjo/pylibjpeg-openjpeg_93f9a1031bbc467692cd36833771bcd2/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/t3/6rfnr3rd6jl7_jg08ppg5h3c0000gq/T/pip-pip-egg-info-lfbbjo5z
         cwd: /private/var/folders/t3/6rfnr3rd6jl7_jg08ppg5h3c0000gq/T/pip-download-3opfmxjo/pylibjpeg-openjpeg_93f9a1031bbc467692cd36833771bcd2/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/t3/6rfnr3rd6jl7_jg08ppg5h3c0000gq/T/pip-download-3opfmxjo/pylibjpeg-openjpeg_93f9a1031bbc467692cd36833771bcd2/setup.py", line 87, in <module>
        setup_oj()
      File "/private/var/folders/t3/6rfnr3rd6jl7_jg08ppg5h3c0000gq/T/pip-download-3opfmxjo/pylibjpeg-openjpeg_93f9a1031bbc467692cd36833771bcd2/setup.py", line 60, in setup_oj
        shutil.copy(
      File "/Users/rjm/miniforge3/envs/aqs-tests-2/lib/python3.8/shutil.py", line 418, in copy
        copyfile(src, dst, follow_symlinks=follow_symlinks)
      File "/Users/rjm/miniforge3/envs/aqs-tests-2/lib/python3.8/shutil.py", line 264, in copyfile
        with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
    FileNotFoundError: [Errno 2] No such file or directory: 'build_tools/cmake/CMakeLists.txt'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/71/e9/94f3d009e9f9f31bb76075641214bdabdbe557b26ce74ff71ef1c28b2c05/pylibjpeg-openjpeg-1.1.1.tar.gz#sha256=e7adfd8e2c63661b75219d5ae381ac50381054df41ca94d0d01ddfbe362a66cc (from https://pypi.org/simple/pylibjpeg-openjpeg/) (requires-python:>=3.6). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading pylibjpeg-openjpeg-1.1.0.tar.gz (2.3 MB)
     |████████████████████████████████| 2.3 MB 5.7 MB/s 
    ERROR: Command errored out with exit status 1:
     command: /Users/rjm/miniforge3/envs/aqs-tests-2/bin/python3.8 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/t3/6rfnr3rd6jl7_jg08ppg5h3c0000gq/T/pip-download-3opfmxjo/pylibjpeg-openjpeg_cafc2c9526f54399948b001f3b4ac833/setup.py'"'"'; __file__='"'"'/private/var/folders/t3/6rfnr3rd6jl7_jg08ppg5h3c0000gq/T/pip-download-3opfmxjo/pylibjpeg-openjpeg_cafc2c9526f54399948b001f3b4ac833/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/t3/6rfnr3rd6jl7_jg08ppg5h3c0000gq/T/pip-pip-egg-info-6b4peu5w
         cwd: /private/var/folders/t3/6rfnr3rd6jl7_jg08ppg5h3c0000gq/T/pip-download-3opfmxjo/pylibjpeg-openjpeg_cafc2c9526f54399948b001f3b4ac833/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/t3/6rfnr3rd6jl7_jg08ppg5h3c0000gq/T/pip-download-3opfmxjo/pylibjpeg-openjpeg_cafc2c9526f54399948b001f3b4ac833/setup.py", line 87, in <module>
        setup_oj()
      File "/private/var/folders/t3/6rfnr3rd6jl7_jg08ppg5h3c0000gq/T/pip-download-3opfmxjo/pylibjpeg-openjpeg_cafc2c9526f54399948b001f3b4ac833/setup.py", line 60, in setup_oj
        shutil.copy(
      File "/Users/rjm/miniforge3/envs/aqs-tests-2/lib/python3.8/shutil.py", line 418, in copy
        copyfile(src, dst, follow_symlinks=follow_symlinks)
      File "/Users/rjm/miniforge3/envs/aqs-tests-2/lib/python3.8/shutil.py", line 264, in copyfile
        with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
    FileNotFoundError: [Errno 2] No such file or directory: 'build_tools/cmake/CMakeLists.txt'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/49/1c/43de9deec30e2a641a3a2f11efa6c13185fa2c77a962676e370a282a3814/pylibjpeg-openjpeg-1.1.0.tar.gz#sha256=66514f5d5df6fdfc704296a8420e4b1feb335fad4e6901435e00c37f353fb44e (from https://pypi.org/simple/pylibjpeg-openjpeg/) (requires-python:>=3.7). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
Collecting pylibjpeg
  Downloading pylibjpeg-1.2.0-py3-none-any.whl (27 kB)
  Downloading pylibjpeg-1.1.1-py3-none-any.whl (29 kB)
  Downloading pylibjpeg-1.1.0-py3-none-any.whl (29 kB)
  Downloading pylibjpeg-1.0.0-py2.py3-none-any.whl (31 kB)
```

**Comment by richard-moss** [comment]
...bit more info (not sure if it's related, but thought I'd throw in in):

when I downloaded the current master, and `python setup.py sdist` the tarball file didn't contain the build_tools directory either.

It also had a cmake error:
```
(aqs-tests-2)  pylibjpeg-openjpeg-master >> python setup.py sdist
CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- The C compiler identification is AppleClang 12.0.5.12050022
-- The CXX compiler identification is AppleClang 12.0.5.12050022
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check if the system is big endian
-- Searching 16 bit integer
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of unsigned short
-- Check size of unsigned short - done
-- Searching 16 bit integer - Using unsigned short
-- Check if the system is big endian - little endian
CMake Error at CMakeLists.txt:71 (include):
  include could not find load file:

    EnsureFileInclude


CMake Error at CMakeLists.txt:73 (ensure_file_include):
  Unknown CMake command "ensure_file_include".


-- Configuring incomplete, errors occurred!
See also "/Users/rjm/Conda-arm-install-stuff/pull-version/pylibjpeg-openjpeg-master/openjpeg/src/openjpeg/build/CMakeFiles/CMakeOutput.log".
See also "/Users/rjm/Conda-arm-install-stuff/pull-version/pylibjpeg-openjpeg-master/openjpeg/src/openjpeg/build/CMakeFiles/CMakeError.log".
```

**Comment by scaramallion** [comment]
Yeah it's not in the `MANIFEST.in` file, I'll fix it up and put out a patch release.

**Comment by richard-moss** [comment]
@scaramallion thanks!

...is that also the cause of `python setup.py sdist` to break when I tried to run manually?

**Comment by jamesrusso** [comment]
Is there any additional information on this? I am attempting to run this as a github action on `ubuntu-latest` and getting the following similar error as above?

``` EnvCommandError

  Command ['/home/runner/work/practiceanalytics-image-conversion/practiceanalytics-image-conversion/.venv/bin/pip', 'install', '--no-deps', '/home/runner/.cache/pypoetry/artifacts/e6/29/38/5e6b3a7fdf89c0c6f7299dbea38863f5a82944b105c9a19791ebcd73b1/pylibjpeg-openjpeg-1.1.1.tar.gz'] errored with the following return code 1, and output: 
  Processing /home/runner/.cache/pypoetry/artifacts/e6/29/38/5e6b3a7fdf89c0c6f7299dbea38863f5a82944b105c9a19791ebcd73b1/pylibjpeg-openjpeg-1.1.1.tar.gz
    Preparing metadata (setup.py): started
    Preparing metadata (setup.py): finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /home/runner/work/practiceanalytics-image-conversion/practiceanalytics-image-conversion/.venv/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-8a1ozfo7/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-8a1ozfo7/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-zh1q6ubl
         cwd: /tmp/pip-req-build-8a1ozfo7/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-8a1ozfo7/setup.py", line 87, in <module>
        setup_oj()
      File "/tmp/pip-req-build-8a1ozfo7/setup.py", line 60, in setup_oj
        shutil.copy(
      File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/shutil.py", line 417, in copy
        copyfile(src, dst, follow_symlinks=follow_symlinks)
      File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/shutil.py", line 254, in copyfile
        with open(src, 'rb') as fsrc:
    FileNotFoundError: [Errno 2] No such file or directory: 'build_tools/cmake/CMakeLists.txt'
    ----------------------------------------
  WARNING: Discarding file:///home/runner/.cache/pypoetry/artifacts/e6/29/38/5e6b3a7fdf89c0c6f7299dbea38863f5a82944b105c9a19791ebcd73b1/pylibjpeg-openjpeg-1.1.1.tar.gz. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  

  at /opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/site-packages/poetry/utils/env.py:1183 in _run
      1179│                 output = subprocess.check_output(
      1180│                     cmd, stderr=subprocess.STDOUT, **kwargs
      1181│                 )
      1182│         except CalledProcessError as e:
    → 1183│             raise EnvCommandError(e, input=input_)
      1184│ 
      1185│         return decode(output)
      1186│ 
      1187│     def execute(self, bin, *args, **kwargs):```

**Comment by scaramallion** [comment]
@jamesrusso can you try installing with the tar archive from GitHub instead: https://github.com/pydicom/pylibjpeg-openjpeg/archive/refs/tags/v1.1.1.tar.gz

Because you're using Python 3.10 pip is falling back on the source files to rebuild, but it looks like it's missing a few files 😞. I'll fix it up when I get a chance

**Comment by jamesrusso** [comment]
Thanks. I was able to get it installed via source in the github action script, but it was a bit messy.

**Comment by hackermd** [comment]
@scaramallion is there a change this could be fixed and an updated packages uploaded to pypi? This issue breaks pip installation of any package that depends on the library.
