### ISSUE TITLE
Pydicom 3.0 and "No module named 'openjpeg' nor 'jpeg_ls'" error

### ISSUE THREAD

**Issue by alanwilter** [pydicom/pylibjpeg-openjpeg#98]
I'm looking for help as everything seems to work fine in my local repo but when I deploy to AWS lambda, I see these error logged:

```

Traceback (most recent call last):
--
File "/var/lang/lib/python3.10/site-packages/pydicom/pixels/utils.py", line 1274, in _passes_version_check
module = importlib.import_module(package_name, "__version__")
File "/var/lang/lib/python3.10/importlib/__init__.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'jpeg_ls'[ERROR]	2024-09-09T16:46:09.666Z		No module named 'jpeg_ls'
Traceback (most recent call last):
File "/var/lang/lib/python3.10/site-packages/pydicom/pixels/utils.py", line 1274, in _passes_version_check
module = importlib.import_module(package_name, "__version__")
File "/var/lang/lib/python3.10/importlib/__init__.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'jpeg_ls'[ERROR]	2024-09-09T16:46:09.666Z		No module named 'openjpeg'
```

My code used to work fine with Pydicom 2.x so I'm looking for any clue to help me solve this issue.

This is the `requirements.txt` that I'm passing to my docker:
```
boto3==1.35.14
boto3-stubs==1.35.14
fpdf2==2.7.9
matplotlib==3.9.2
matplotlib-inline==0.1.7
mypy-boto3-cloudformation==1.35.0
mypy-boto3-dynamodb==1.35.0
mypy-boto3-ec2==1.35.8
mypy-boto3-lambda==1.35.3
mypy-boto3-rds==1.35.0
mypy-boto3-s3==1.35.2
mypy-boto3-sqs==1.35.0
natsort==8.4.0
opencv-python-headless==4.10.0.84
pydicom==3.0.0
pylibjpeg==2.0.1
pylibjpeg-libjpeg==2.2.0
types-fpdf2==2.7.9.20240813
```

Previously, working set was:
```
boto3==1.34.89
boto3-stubs==1.34.89
fpdf2==2.7.8
matplotlib==3.8.4
matplotlib-inline==0.1.7
mypy-boto3-cloudformation==1.34.84
mypy-boto3-dynamodb==1.34.67
mypy-boto3-ec2==1.34.86
mypy-boto3-lambda==1.34.77
mypy-boto3-rds==1.34.83
mypy-boto3-s3==1.34.65
mypy-boto3-sqs==1.34.0
natsort==8.4.0
opencv-python-headless==4.9.0.80
pydicom==2.4.4
pylibjpeg==2.0.0
pylibjpeg-libjpeg==2.1.0
types-fpdf2==2.7.8.20240406
```

**Comment by mrbean-bremen** [comment]
As far as I can see, this is just unfortunate logging in pydicom (the exception is caught but logged, including the callstack) while checking if a package is installed. If the logging bothers you, you could add `pylibjpeg-openjpeg` and `pyjpegls` to your requirements as a workaround. I'm transferring this issue to `pydicom`.
